name: "Terraform Infrastructure Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: "dev-ai-model-repo"

jobs:
  # Job 0: Detect changes in the infrastructure & app directories
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      app: ${{ steps.filter.outputs.app }}
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infra:
              - 'infrastructure/**'
            app:
              - 'app/**'
            api:
              - 'api/**'
  
  # Job 1: Deploy infrastructure if there are changes in the infrastructure directory
  create-ecr:
    needs: detect_changes
    if: needs.detect_changes.outputs.infra == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/envs/dev
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.3
      - run: terraform init
      - run: terraform apply -target="module.container_registry" -auto-approve    

  # Job 2: Build and push Docker image if there are changes in the app directory
  build-and-push:
    needs: [detect_changes, create-ecr]
    if: |
      always() &&
      needs.detect_changes.outputs.app == 'true' &&
      (needs.create-ecr.result == 'success' || needs.create-ecr.result == 'skipped')
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.COMMIT_SHORT_SHA }}
    steps:
      - uses: actions/checkout@v4
      - name: Set short SHA for image tag
        id: vars
        run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.vars.outputs.COMMIT_SHORT_SHA }}
        working-directory: ./app
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # Job 3: Deploy infrastructure if there are changes in the infrastructure directory or if the Docker image was built successfully
  deploy-infra:
    needs: [detect_changes, build-and-push]
    if: |
      always() &&
      (needs.detect_changes.outputs.infra == 'true' || needs.detect_changes.outputs.app == 'true' || needs.detect_changes.outputs.api == 'true') &&
      (needs.build-and-push.result == 'success' || needs.build-and-push.result == 'skipped')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/envs/dev
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.3
      - run: terraform init
      - name: Terraform Apply
        env:
          TF_VAR_image_tag: ${{ needs.build-and-push.outputs.image_tag || 'latest' }}
        run: terraform apply -auto-approve